package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"ai-router/internal/config"
	"gopkg.in/yaml.v3"
)

const aggregationFile = "aggregation.yaml"

// Save writes .env and aggregation.yaml from SetupConfig.
func Save(sc *SetupConfig, dir string) error {
	if err := saveEnv(sc, dir); err != nil {
		return fmt.Errorf("save .env: %w", err)
	}
	if err := saveAggregation(sc, dir); err != nil {
		return fmt.Errorf("save aggregation.yaml: %w", err)
	}
	return nil
}

func saveEnv(sc *SetupConfig, dir string) error {
	var b strings.Builder

	// Header
	b.WriteString("# AI Router Gateway - Generated by aimux setup\n\n")

	// Gateway
	b.WriteString("# ---- Gateway Settings ----\n")
	fmt.Fprintf(&b, "GATEWAY_HOST=%s\n", sc.Gateway.Host)
	fmt.Fprintf(&b, "GATEWAY_PORT=%d\n", sc.Gateway.Port)
	fmt.Fprintf(&b, "DEBUG=%t\n", sc.Gateway.Debug)
	b.WriteString("\n")

	// Routing
	b.WriteString("# ---- Routing ----\n")
	fmt.Fprintf(&b, "ROUTING_STRATEGY=%s\n", sc.Routing.Strategy)
	fmt.Fprintf(&b, "FALLBACK_ON_ERROR=%t\n", sc.Routing.FallbackOnError)
	fmt.Fprintf(&b, "MAX_RETRIES=%d\n", sc.Routing.MaxRetries)
	b.WriteString("\n")

	// Model Mapping
	b.WriteString("# ---- Model Mapping ----\n")
	b.WriteString("BIG_MODEL=gpt-4o\n")
	b.WriteString("MIDDLE_MODEL=gpt-4o\n")
	b.WriteString("SMALL_MODEL=gpt-4o-mini\n")
	b.WriteString("\n")

	// Providers
	for _, p := range sc.Providers {
		prefix := ProviderPrefix(p.Name)
		fmt.Fprintf(&b, "# ---- Provider: %s ----\n", p.Name)
		fmt.Fprintf(&b, "%s_ENABLED=%t\n", prefix, p.Enabled)
		if p.BaseURL != "" {
			fmt.Fprintf(&b, "%s_BASE_URL=%s\n", prefix, p.BaseURL)
		}
		if p.APIKey != "" {
			fmt.Fprintf(&b, "%s_API_KEY=%s\n", prefix, p.APIKey)
		}
		if p.Model != "" {
			fmt.Fprintf(&b, "%s_MODEL=%s\n", prefix, p.Model)
		}
		if p.Weight > 0 {
			fmt.Fprintf(&b, "%s_WEIGHT=%d\n", prefix, p.Weight)
		}
		if p.Priority > 0 {
			fmt.Fprintf(&b, "%s_PRIORITY=%d\n", prefix, p.Priority)
		}
		if p.Timeout > 0 {
			fmt.Fprintf(&b, "%s_TIMEOUT=%d\n", prefix, p.Timeout)
		}
		if p.AutoModel {
			fmt.Fprintf(&b, "%s_AUTO_MODEL=true\n", prefix)
		}
		if p.Passthrough {
			fmt.Fprintf(&b, "%s_PASSTHROUGH=true\n", prefix)
		}
		b.WriteString("\n")
	}

	// Circuit Breaker
	b.WriteString("# ---- Circuit Breaker ----\n")
	fmt.Fprintf(&b, "FAILURE_THRESHOLD=%d\n", sc.CircuitBreaker.FailureThreshold)
	fmt.Fprintf(&b, "COOLDOWN_SECONDS=%.0f\n", sc.CircuitBreaker.CooldownSeconds)
	fmt.Fprintf(&b, "HEALTH_CHECK_INTERVAL=%.0f\n", sc.CircuitBreaker.HealthCheckInterval)
	b.WriteString("\n")

	// Rate Limiting
	b.WriteString("# ---- Rate Limiting ----\n")
	fmt.Fprintf(&b, "RATE_LIMIT_ENABLED=%t\n", sc.RateLimit.Enabled)
	fmt.Fprintf(&b, "RATE_LIMIT_RPM=%d\n", sc.RateLimit.RPM)
	fmt.Fprintf(&b, "RATE_LIMIT_BURST=%d\n", sc.RateLimit.Burst)
	b.WriteString("\n")

	// Auth
	b.WriteString("# ---- Client Auth ----\n")
	if len(sc.Auth.ValidAPIKeys) > 0 {
		keys := make([]string, len(sc.Auth.ValidAPIKeys))
		copy(keys, sc.Auth.ValidAPIKeys)
		fmt.Fprintf(&b, "VALID_API_KEYS=%s\n", joinKeysJSON(keys))
	} else {
		b.WriteString("VALID_API_KEYS=[]\n")
	}
	b.WriteString("\n")

	// Config file reference
	b.WriteString("# ---- Aggregation Config ----\n")
	b.WriteString("CONFIG_FILE=" + aggregationFile + "\n")

	return os.WriteFile(filepath.Join(dir, ".env"), []byte(b.String()), 0644)
}

func saveAggregation(sc *SetupConfig, dir string) error {
	if len(sc.Aggregations) == 0 {
		// Write empty aggregation file.
		return os.WriteFile(filepath.Join(dir, aggregationFile), []byte("# Model aggregations\nmodel_aggregations: []\n"), 0644)
	}

	type yamlEntry struct {
		Provider string `yaml:"provider"`
		Model    string `yaml:"model"`
		Weight   int    `yaml:"weight"`
	}
	type yamlAgg struct {
		Name     string       `yaml:"name"`
		Strategy string       `yaml:"strategy"`
		Models   []yamlEntry  `yaml:"models"`
	}

	var out []yamlAgg
	for _, agg := range sc.Aggregations {
		ya := yamlAgg{Name: agg.Name, Strategy: agg.Strategy}
		for _, m := range agg.Models {
			ya.Models = append(ya.Models, yamlEntry{
				Provider: m.Provider, Model: m.Model, Weight: m.Weight,
			})
		}
		out = append(out, ya)
	}

	data, err := yaml.Marshal(struct {
		Aggregations []yamlAgg `yaml:"model_aggregations"`
	}{out})
	if err != nil {
		return err
	}

	header := "# aggregation.yaml - Generated by aimux setup\n#\n# Model aggregations create virtual models that route across providers\n# using different strategies (weighted, fallback, round_robin).\n\n"
	return os.WriteFile(filepath.Join(dir, aggregationFile), append([]byte(header), data...), 0644)
}

func joinKeysJSON(keys []string) string {
	// Format: ["key1","key2"]
	quoted := make([]string, len(keys))
	for i, k := range keys {
		quoted[i] = `"` + k + `"`
	}
	return "[" + strings.Join(quoted, ",") + "]"
}

// AggregationFile returns the default aggregation file path relative to dir.
func AggregationFile() string {
	return aggregationFile
}

// DefaultAggregation creates a default "codex" aggregation entry.
func DefaultAggregation() config.ModelAggregation {
	return config.ModelAggregation{
		Name: "codex", Strategy: "weighted",
		Models: []config.ModelAggEntry{
			{Provider: "codex", Model: "gpt-5.5", Weight: 100},
		},
	}
}
